### ISSUE TITLE
does not compile with newer ffmpeg versions (FF_INPUT_BUFFER_PADDING_SIZE)

### ISSUE THREAD

**Issue by macearl** [Moonbase59/loudgain#1]
for newer ffmpeg versions FF_INPUT_BUFFER_PADDING_SIZE in scan.c needs to be renamed to AV_INPUT_BUFFER_PADDING_SIZE to be able to compile again

**Comment by Moonbase59** [comment]
Good find and thanks for the feedback! And you’re actually correct since libavresample has been deprecated for a while but I didn’t get around changing the code to work with FFmpeg’s libswresample yet.

So, yes, for the time being you _might_ need to do the above change. (Usually the case on rolling releases like Arch or Manjaro that have the newest software.)

I still plan to rework it, so it’ll cleanly compile using the newer libraries.

**Comment by macearl** [comment]
ah so ideally in the future libavresample will be dropped completely from the dependencies?

**Comment by Moonbase59** [comment]
Yes, that’s the plan. But it’ll use libswresample instead ;-)

**Comment by macearl** [comment]
of course, its just that libswresample is included in my ffmpeg package, whereas libavresample is not anymore due to it being deprecated.

I'll keep an eye out for future versions.

**Comment by Moonbase59** [comment]
That’s exactly the point. It was a kludge in the first place, since some distros dropped FFmpeg for some years, most notably Ubuntu … Now that everyone is back using FFmpeg we will also. :-)

**Comment by Moonbase59** [comment]
What kind and version of Linux are you building on?

Would you do me a favour and test out the "libswresample" branch?

If you kept your git-cloned folder, this should be as easy as:
```bash
git checkout libswresample
cd build
cmake ..
make
sudo make install
```

There are still a few deprecated calls in `scan.c` which I plan to clean out in the long run, but this version did cleanly build here on Ubuntu 18.04, Linux Mint 19.1 and Manjaro 18.0.4, using `libswresample` instead of `libavresample`.

**Comment by macearl** [comment]
Seems to work fine (tested just one Album of flac files).

Im running Arch Linux, so not really a surprise that it works if you already tested it on manjaro

**Comment by Moonbase59** [comment]
Good to know, let me know if you find any more problems!

**Comment by macearl** [comment]
if there are any i should know in an hour or so, i just started the rgbpm.sh script on my complete music collection ;)

**Comment by Moonbase59** [comment]
Woohaa, one of the brave! Good luck (and I do hope you have a backup, read all the docs, and remember there are no warranties …) :-)

Fortunately, using Arch, your taglib will be new enough not to expose the Ogg Vorbis corruption bug (just in case you have some).

**Comment by macearl** [comment]
yeah i got a backup.

Everything seems to have worked fine, all files i checked got the replaygain tags written and the old ones removed.

It just took quite a bit longer than i expected, but i just let the computer do its thing and just checked on it again.

**Comment by Moonbase59** [comment]
Good to hear, thanks for testing and feedback!
